microsoft/Web-Dev-For-Beginners

4-typing-game/typing-game/README.md
6-space-game/1-introduction/README.md

Howdy! There were some broken links to supporting gifs/images in some of the docs- these were some of the immediate ones I found. Are these the correct assets for the two .md files?

Fixing broken links to assets

---

1-getting-started-lessons/2-github-basics/README.md

The *Introduction to GitHub* readme has a broken image link, incorrectly referencing the images folder. The local `images` folder was referenced as `/images/...` instead of `images/...`.

Fix broken image link in Introduction to GitHub

---

1-getting-started-lessons/1-intro-to-programming-languages/README.md
1-getting-started-lessons/2-github-basics/README.md
1-getting-started-lessons/3-accessibility/README.md
2-js-basics/1-data-types/README.md
2-js-basics/2-functions-methods/README.md
2-js-basics/3-making-decisions/README.md
2-js-basics/4-arrays-loops/README.md
3-terrarium/1-intro-to-html/README.md
3-terrarium/2-intro-to-css/README.md
3-terrarium/3-intro-to-DOM-and-closures/README.md
4-typing-game/typing-game/README.md
5-browser-extension/1-about-browsers/README.md
5-browser-extension/2-forms-browsers-local-storage/README.md
5-browser-extension/3-background-tasks-and-performance/README.md
6-space-game/1-introduction/README.md
6-space-game/2-drawing-to-canvas/README.md
6-space-game/3-moving-elements-around/README.md
6-space-game/4-collision-detection/README.md
6-space-game/5-keeping-score/README.md
6-space-game/6-end-condition/README.md
7-bank-project/1-template-route/README.md
7-bank-project/2-forms/README.md
7-bank-project/3-data/README.md
7-bank-project/4-state-management/README.md

Pre/Post quizzes links were broken. As an example the URLs were like `1-getting-started-lessons/1-intro-to-programming-languages/.github/...`, but actually they must be like   `/.github/...`.

Fix broken quiz links

---

6-space-game/2-drawing-to-canvas/README.md

Hi, I made a small fix in the example code of 6-space-game/2-drawing-to-canvas/README.md
The corresponding code in 6-space-game/2-drawing-to-canvas/solution/app.js looks fine.
1. move `resolve(img)` in loadAsset function to the inside of the img.onload function to resolve the promise after the image is loaded
2. remove the async keyword of loadAsset because it is not that harmful but not yet necessary

fix loadAsset function in 6-space-game/2-drawing-to-canvas/README.md

---

1-getting-started-lessons/3-accessibility/.github/pre-lecture-quiz.md
1-getting-started-lessons/3-accessibility/README.md

❤️ having an accessibility section in a web dev course! I reviewed the content, and created the following suggested updates (with reasons detailed below):
- **Removed the word "physical" from "screen reader"**
- **Updated the wording about browser text reading tools**
The reason for this is because the functionality and usage of tools like Edge's speak aloud feature and other text reading extensions are fundamentally different from screen readers. They are not primarily used for vision-related disabilities, and provide a very different UX and have different accessibility considerations than screen readers do. Since people who are new to accessibility sometimes confuse simpler text-reading tools for screen readers, I wanted to make the difference more clear in the tutorial wording.
- …

Proposed content changes to the accessibility unit

---

3-terrarium/1-intro-to-html/README.md

the link in "deprecated tags such as [these tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element)" currently links to the list of all HTML elements with the deprecated and obsolete ones at the very bottom which is kinda confusing. This PR changes the link to go directly to the section on [obsolete and deprecated elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element#Obsolete_and_deprecated_elements).

Link specifically to deprecated tags in intro to HTML

---

3-terrarium/3-intro-to-DOM-and-closures/README.md

Function's name in the instructions was "closeElementDrag", corrected it to "StopElementDrag", which is what it's called in the Javascript file.

Change function's name to what is called in Javascript.

---

7-bank-project/README.md
7-bank-project/translations/README.es.md
7-bank-project/translations/README.ko.md

Using "<img src />" HTML cannot guarantee relative paths.
The issue is being investigated but using a markdown table format
would be an alternative approach.
- FYI: https://github.com/docsifyjs/docsify/issues/850

Use markdown table format to display images instead

---

index.html

This configuration solves "404 - Not found" issues browsing files
using "docsify serve" command for offline access.
See configuration details on docsify documentation:
- https://docsify.js.org/#/configuration?id=relativepath

Trivial: Enable relativePath conf in docsify

---

quiz-app/src/components/Quiz.vue
quiz-app/src/views/Home.vue

- When I click another language option in quiz component, the quiz sentence is not changed to another language.
- Translation json files have 'title' and 'id' fields each quiz, but not using this fields.
- Update questions `data` -> `computed` on Quiz component.
- Refactor Home component using v-for
- #130

Fix questions data re-rendering & Refactor home component (on quiz-app)

---

quiz-app/src/App.vue

When App component is created not using query parameter 'loc', locale data is '' (empty).
Add checking logic $route.query.loc
https://github.com/microsoft/Web-Dev-For-Beginners/pull/140#issuecomment-753474895

fix empty locale option when first created (quiz-app)

---

6-space-game/4-collision-detection/solution/app.js
6-space-game/5-keeping-score/solution/app.js
6-space-game/5-keeping-score/your-work/app.js
6-space-game/6-end-condition/solution/app.js
6-space-game/6-end-condition/your-work/app.js

I'm not sure if PRs like these are considered, but this fixes a minor laser cooldown bug that's already fixed in [6-space-game/solution/app.js](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/6-space-game/solution/app.js) (lines 307-309) but not in the lessons' individual app.js files.
**Describe the bug**
Pressing space bar before the laser's cooldown is over will result in the cooldown being nullified, letting the ship shoot much faster than the cooldown should allow.
**To Reproduce**
1. Open 'index.html'
2. Press space bar very quickly
**Screenshot**
[Result of quickly pressing space bar](https://i.imgur.com/ofGVwy9.png)
(intended cooldown is 1200 ms)

Fix laser cooldown bug

---

5-browser-extension/1-about-browsers/README.md
5-browser-extension/1-about-browsers/translations/README.it.md
5-browser-extension/1-about-browsers/translations/assignment.it.md
5-browser-extension/2-forms-browsers-local-storage/translations/README.it.md
5-browser-extension/2-forms-browsers-local-storage/translations/assignment.it.md
5-browser-extension/3-background-tasks-and-performance/README.md
5-browser-extension/3-background-tasks-and-performance/translations/README.it.md
5-browser-extension/3-background-tasks-and-performance/translations/assignment.it.md
5-browser-extension/solution/README copy.md
5-browser-extension/solution/translation/README.it.md
5-browser-extension/start/dist/background.js
5-browser-extension/start/dist/index.html
5-browser-extension/start/src/index.js
5-browser-extension/start/translations/README.it.md
5-browser-extension/translations/README.it.md

Hi, 
just a thought regarding the extension installation instructions: maybe it's worth specify that you have to enable "Developer mode" first in order to see "Load unpacked", by default this mode is disabled. You can see this in the screenshot anyway but after all we are addressing beginners...
1-about browser
- After "Take a minute to look through the codebase:" may a code block directive is missing when you specify the directory structure of the app?
- "build your extension using npm build" should be "build your extension using npm **run** build"?
3-background task and performance
- This link is broken:
You'll learn more about the Canvas API in the [Space Game lessons](../../space-game/drawing-to-canvas/README.md).
I think should be
You'll learn more about the Canvas API in the [Space …

Italian Translation - Ch. 5

---

2-js-basics/4-arrays-loops/README.md
2-js-basics/translations/README.de.md
2-js-basics/translations/README.es.md
2-js-basics/translations/README.it.md
2-js-basics/translations/README.ja.md
2-js-basics/translations/README.ms.md

Links appeared to be broken. It looks like translations are still a work in progress throughout so I only fixed a couple that I noticed while going through the js-basics lesson.

Fix Markdown translation links in js-basics lesson

---

7-bank-project/1-template-route/README.md
7-bank-project/1-template-route/translations/README.hi.md
7-bank-project/1-template-route/translations/README.it.md
7-bank-project/1-template-route/translations/README.ja.md
7-bank-project/1-template-route/translations/README.ms.md
7-bank-project/1-template-route/translations/README.zh-tw.md

Event must be passed as argument when binding `onClickLink` to `onclick` attribute, otherwise `event` is undefined and an error is thrown on `event.preventDefault()`.

Fix missing event argument in Banking App Part 1

---

.github/workflows/azure-static-web-apps-nice-beach-0fe9e9d0f.yml

Disable PR deployment as it's in error for all external PRs (will still work on main branches commits or merges)

Disable deployment on PR

---

1-getting-started-lessons/translations/README.ru.md

Fixes:
added links to Russian lessons (available at the moment) in `1-getting-started-lessons`

fix: added links to russian lessons

---

2-js-basics/1-data-types/README.md

Hello.
I wonder if `null` should be added as a primitive type.
According to the Javascript [Specification](https://tc39.es/ecma262/#sec-null-value):
```
null is a primitive value that represents the intentional absence of any object value
```
This PR was created within Hacktoberfest. thx

added null as primitive type

---

5-browser-extension/2-forms-browsers-local-storage/README.md

In Lines 9, 15, 144, and 198, I fixed the verb form to correct the grammar.
> Line 9: `display` -> `displaying`
> Line 15: `building` -> `build`
> Line 144: `are` -> `is`
> Line 198: `by call` -> `by calling`
In Lines 107, 142, and 148,  I added a `,` to separate the sentences.
> Line 107: getItem(), setItem() or removeItem() -> getItem(), setItem() `,` or removeItem()
> Line 142: Finally it's time to query the API! -> Finally `,` it's time to query the API!
> Line 148: First notice the async keyword -> First `,` notice the async keyword
In Line 219, I fixed the preposition to correct the grammar.
> Can you think how these two things work together? -> Can you think `about how` these two things work together?

Fix Typos and Grammar in Browser Extension Project Part 2

---

1-getting-started-lessons/1-intro-to-programming-languages/translations/README.es.md
1-getting-started-lessons/2-github-basics/translations/README.es.md
1-getting-started-lessons/translations/README.es.md

There are three links in the README.es that lead to the English version. With this update, they now redirect to the Spanish version.

Fix links to topics in the correct language

---

7-bank-project/solution/README.md

If you would follow the old instructions you could end up in the wrong directory.

bank project solution, describe in more detail how to start it

---

2-js-basics/3-making-decisions/README.md

Working through the JavaScript section, specifically in "making-decisions", and noticed a missing space in the README.md file between sentences. 
Added the missing space in the "making-decisions" README.md file.
- This change requires a documentation update - fixed grammatical error in documentation README

Fix Typo: added a space in "making-decisions" README file

---

1-getting-started-lessons/1-intro-to-programming-languages/translations/README.zh-cn.md

wrong image URL in intro to programming README.zh-cz
before
after
Fixes #1184 
- [X ] Bug fix (non-breaking change which fixes an issue)

fix: wrong image url in intro to programming README.zh-cz

---

2-js-basics/3-making-decisions/README.md

Used appropriate words to make sentence better and fixed a typo.

Fix typos & grammatical corrections

---

1-getting-started-lessons/1-intro-to-programming-languages/README.md

Regarding this issue:
Incorrect link text #1260
Fixed the issue of link showing wrong description of "www.sublimetext" to Sublime text.
I have changed the incorrect spelling in the Readme.md file. The link text was starting with www instead of just Sublimetext.
I have removed www. from the link text.

Link text for Sublime text has been fixed.

---

4-typing-game/solution/index.js
7-bank-project/solution/app.js

This pull request resolves issue #1384 by removing a broken API request in the `7.bank/solution` directory. The API request was not functional and caused the login template to fail. Since the API was unnecessary for the learning objective of this lesson, it has been removed to ensure the solution runs smoothly.
Fixes #1384

Fix: Removed broken API request from 7.bank solution (Fixes #1384)

---

1-getting-started-lessons/1-intro-to-programming-languages/README.md
1-getting-started-lessons/1-intro-to-programming-languages/assignment.md
2-js-basics/1-data-types/assignment.md
3-terrarium/1-intro-to-html/assignment.md
3-terrarium/2-intro-to-css/assignment.md
3-terrarium/solution/index.html
3-terrarium/solution/style.css
4-typing-game/solution/index.css
4-typing-game/solution/index.html
4-typing-game/solution/index.js
6-space-game/2-drawing-to-canvas/solution/app.js
6-space-game/2-drawing-to-canvas/solution/index.html
6-space-game/solution/app.js
6-space-game/solution/index.html
7-bank-project/solution/app.js
7-bank-project/solution/index.html
7-bank-project/solution/styles.css
8-code-editor/1-using-a-code-editor/README.md
9-chat-project/solution/backend/python/api.py
9-chat-project/solution/backend/python/llm.py
9-chat-project/solution/frontend/index.html
for-teachers.md
index.css
index.html

Upgraded typing game, chat backend, and main index files
