- README.md
- TRANSLATIONS.md
As suggested in issue #7 by @jlooper, I added a translation guideline that is linked from the main README.md.
> Added Translation guideline

- 1-getting-started-lessons/2-github-basics/README.md
- 3-terrarium/1-intro-to-html/README.md
Added commands for git bash/ terminal to make a dir/ folder and index.html file.
Fixed sentence structure and missing words or tags.
Added correct info on alt tag.
> Added commands for git bash, fixed sentence structure and added info on alt tag.

- 4-typing-game/README.md
- 4-typing-game/typing-game/README.md
Fixed #42 
Added  missing closed div tag in index.html example in readme file
> Added missing div tag

- 1-getting-started-lessons/1-intro-to-programming-languages/.github/post-lecture-quiz.md
- 1-getting-started-lessons/1-intro-to-programming-languages/.github/pre-lecture-quiz.md
Hello ,I found out this minor typo and fixed it.
Hope it helps.
In  1-getting-started-lessons/1-intro-to-programming-languages/.github
Corrected:
> Corrected the numbering in the  pre/post quiz

- 3-terrarium/1-intro-to-html/README.md
> Replace link to image folder

- 1-getting-started-lessons/2-github-basics/README.md
Added commands for staging a particular file and unstaging a file or multiple files
> Added commands for staging a particular file and unstaging a file or multiple files

- 4-typing-game/typing-game/README.md
Typing game README example code doesn't work.
> Update Typing game README.md

- 2-js-basics/1-data-types/README.md
- 2-js-basics/1-data-types/translations/README.de.md
- 2-js-basics/1-data-types/translations/README.es.md
> Fix typo in readme 

- 2-js-basics/translations/README.de.md
The last sequence of words did not made a complete sentence. I just added the verb of the sentence to this sequence.
> Small improvement of the german Readme.md

- 3-terrarium/3-intro-to-DOM-and-closures/assignment.md
added a "t" so that there was no typo and misunderstanding using the term "adoping"
> Fixing typo from "adoping" to "adopting"

- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.nl.md
Quizzes and assignments are not translated yet.
@FloorD do you want to review?
> Translated 1-intro-to-programming-languages into Dutch

- 3-terrarium/1-intro-to-html/README.md
- 4-typing-game/solution/index.html
- 4-typing-game/typing-game/README.md
- 5-browser-extension/1-about-browsers/README.md
- 5-browser-extension/3-background-tasks-and-performance/README.md
- 5-browser-extension/solution/dist/index.html
- 6-space-game/solution/index.html
- 7-bank-project/1-template-route/README.md
- 7-bank-project/2-forms/README.md
- 7-bank-project/3-data/README.md
- 7-bank-project/4-state-management/assignment.md
- 7-bank-project/api/package-lock.json
- 7-bank-project/solution/index.html
I'm back again with some more accessibility updates 😅. These are split into roughly two categories:
1. Updates to wording (including some random spelling fixes I came across while reading)
2. Updates to the HTML of the examples and solutions
The wording changes mostly fall into the following categories:
- Updates that are necessary due to changing the HTML
- Wording choices that (based on my own understanding) are likely to go over better with the disabled community
- Updates to instructions that reference screenshots to ensure they don't rely only on visual things like color/iconography/shape
The code changes mostly revolve around labeling form controls and the judicious use of semantic elements.
Please let me know if you have any questions/comments on any specific changes! I also know …
> Accessibility updates in lessons 3-7

- 3-terrarium/translations/README.es.md
- 5-browser-extension/translations/README.es.md
- 6-space-game/translations/README.es.md
just add the correct folders to the links.
> fix several broken image-links

- 2-js-basics/3-making-decisions/README.md
- 2-js-basics/4-arrays-loops/README.md
The "pre-lecture Quiz" and "Post-Lecture Quiz " phrases where in a different line and was not having the benefit of the ``` ## ``` . So this is the fix.
> Pre post lecture edit

- 2-js-basics/3-making-decisions/README.md
> Replaced ` with ; in line 128.

- quiz-app/src/assets/translations/id.json
I will double check the translation, after we finish translating the main sections to Indonesian.
Ready to merge.
> Indonesian translations for quiz-app

- 3-terrarium/2-intro-to-css/README.md
This is similar to the pr i had done 4 days ago ( #134  )
> Added https:// which has a similar problem as #134

- 1-getting-started-lessons/2-github-basics/README.md
Fix a few grammatical mistakes in **[/getting-started-lessons/2-github-basics/README.md](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/1-getting-started-lessons/2-github-basics/README.md)**
> Fix a few grammatical mistakes

- quiz-app/src/assets/translations/index.js
- quiz-app/src/assets/translations/ja.json
Hi.
I translate quiz-app into japanese.
This pull request is OK to merge.
How about this?
> translate quiz-app into japanese

- 7-bank-project/3-data/README.md
Fix typos in lesson text and used generic language for input methods for accessibility.
> Fix language in lesson 23 (Banking App - Data)

- 4-typing-game/translations/README.ko.md
- 4-typing-game/typing-game/translations/README.ko.md
by mistake, missing translation. 
Translated typing game. And also fixed link error.
> Add typing-game ko translation

- 1-getting-started-lessons/3-accessibility/translations/README.ja.md
- 2-js-basics/1-data-types/translations/README.ja.md
- 2-js-basics/2-functions-methods/translations/README.ja.md
- 2-js-basics/3-making-decisions/translations/README.ja.md
- 2-js-basics/4-arrays-loops/translations/README.ja.md
- 3-terrarium/1-intro-to-html/translations/README.ja.md
- 3-terrarium/2-intro-to-css/translations/README.ja.md
- 3-terrarium/3-intro-to-DOM-and-closures/translations/README.ja.md
- 4-typing-game/typing-game/translations/README.ja.md
- 5-browser-extension/1-about-browsers/translations/README.ja.md
- 5-browser-extension/2-forms-browsers-local-storage/translations/README.ja.md
- 5-browser-extension/3-background-tasks-and-performance/translations/README.ja.md
- 6-space-game/1-introduction/translations/README.ja.md
- 6-space-game/2-drawing-to-canvas/translations/README.ja.md
- 6-space-game/3-moving-elements-around/translations/README.ja.md
- 6-space-game/4-collision-detection/translations/README.ja.md
- 6-space-game/5-keeping-score/translations/README.ja.md
- 6-space-game/6-end-condition/translations/README.ja.md
- 7-bank-project/1-template-route/translations/README.ja.md
- 7-bank-project/2-forms/translations/README.ja.md
- 7-bank-project/3-data/translations/README.ja.md
- 7-bank-project/4-state-management/translations/README.ja.md
Hi.
I fixed pre and post quiz-url.
This pull request is OK to merge.
How about this?
> fix quiz url.

- 3-terrarium/1-intro-to-html/translations/README.it.md
- 3-terrarium/1-intro-to-html/translations/assignment.it.md
- 3-terrarium/2-intro-to-css/translations/README.it.md
- 3-terrarium/2-intro-to-css/translations/assignment.it.md
- 3-terrarium/3-intro-to-DOM-and-closures/translations/README.it.md
- 3-terrarium/3-intro-to-DOM-and-closures/translations/assignment.it.md
- 3-terrarium/translations/README.it.md
Jen, here's the translation for the 3rd chapter.
You may want to check this (sorry if I misinterpreted):
Chapter 3.1 (assignment.md)
"Create a graphical markup of your site"  maybe should  be "Create a graphical *mock up* of your site"?
Chapter 3.2 (readme.md): some language specs for the code markup are missing, the syntax highlighting is not rendered, for example \```css is missing here:
"Set the body's font to a given font, and check to see a nested element's font:
\```
body {
font-family: helvetica, arial, sans-serif;
}
\```
"
Chapter 3.3 (assignment.md)
"Visit the MSDN's list of DOM interfaces and pick one" maybe should be "Visit the *MDN*'s list of DOM interfaces and pick one"
Thanks!
> Italian translation of chapter 3

- 5-browser-extension/solution/package.json
updated axios dependency to fix the dependabot vulnerability.
> fix: dependabot vulnerablity

- 1-getting-started-lessons/2-github-basics/README.md
while reading through the curriculum found and fixed a typo.
> fix spelling in **check status ** step

- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.gr.md
- quiz-app/src/App.vue
- quiz-app/src/assets/translations/gr.json
- quiz-app/src/assets/translations/index.js
> translated all quiz questions to greek

- quiz-app/src/App.vue
- quiz-app/src/assets/translations/es.json
- quiz-app/src/assets/translations/index.js
- Added my translations to the quiz-app by adding following ES file: https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/quiz-app/src/assets/translations/es.json 
- Added my Spanish (ES) language code to the dropdown in the quiz-app's App.vue file
- Edited the quiz-app's translations index.js file to add my language
> Quizzes translated to Spanish

- 1-getting-started-lessons/3-accessibility/translations/README.es.md
> fix image url

- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.fr.md
- 1-getting-started-lessons/1-intro-to-programming-languages/translations/assignment.fr.md
- 1-getting-started-lessons/translations/README.fr.md
- translations/for-teachers.fr.md
Each lesson includes a translation of the README.md and the Assignment.md file, if available. Only mark the lesson complete if both those files are translated per lesson, please.
> Adding FR.fr

- quiz-app/src/App.vue
- quiz-app/src/assets/translations/index.js
- quiz-app/src/assets/translations/zh_cn.json
- quiz-app/src/assets/translations/zh_tw.json
- Translate all quizzes to Simplified Chinese following the [Guidelines](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/TRANSLATIONS.md)
- Fix some mistakes in the Traditional Chinese translation (@CRTao PTAL)
- Quiz App tested on my PC, everything works fine 😀
> Quizzes translated to Simplified Chinese

- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.es.md
Add various fixes.
- Eliminate neutrality.
- Correct spelling mistakes.
- Modify words of proper names (assembly).
> Add several modifications regarding the Spanish language.

- 7-bank-project/1-template-route/README.md
I was reading through the lesson on templates and routes, and found a few small things that I think could be a tiny bit clearer.
> Small writing tweaks

- 1-getting-started-lessons/2-github-basics/translations/README.pt.md
docs update => proper capitalisation would be better. 👍: Github
Signed-off-by: Ayushman Singh Chauhan <ascb508@gmail.com>
> DOC: Fix camelCase (or capitalization)

- 1-getting-started-lessons/3-accessibility/assignment.md
Table was formatted weird that it wasn't MD accessible, and assignment instructions had misspellings and bad formatting
> Fix table formatting and spelling mistakes

- 5-browser-extension/3-background-tasks-and-performance/README.md
- 5-browser-extension/3-background-tasks-and-performance/translations/README.es.md
- 5-browser-extension/3-background-tasks-and-performance/translations/README.ms.md
- 5-browser-extension/3-background-tasks-and-performance/translations/README.zh.tw.md
Fixed reference link to canvas lesson in main readme and translations
> Fix: corrected reference link from canvas lesson

- 3-terrarium/1-intro-to-html/translations/README.zh-cn.md
👋 Hi
I am very enthusiastic about this project and hope to translate some simplified Chinese content every week. It is really fun.
> Translation zh-cn

- 5-browser-extension/solution/package.json
> Bump glob-parent to 5.1.2

- 2-js-basics/4-arrays-loops/README.md
- 2-js-basics/4-arrays-loops/translations/README.de.md
- 2-js-basics/4-arrays-loops/translations/README.es.md
- 2-js-basics/4-arrays-loops/translations/README.hi.md
- 2-js-basics/4-arrays-loops/translations/README.id.md
- 2-js-basics/4-arrays-loops/translations/README.it.md
- 2-js-basics/4-arrays-loops/translations/README.ja.md
- 2-js-basics/4-arrays-loops/translations/README.ko.md
- 2-js-basics/4-arrays-loops/translations/README.ms.md
- 2-js-basics/4-arrays-loops/translations/README.zh-cn.md
- 2-js-basics/4-arrays-loops/translations/README.zh-tw.md
> Updated Incorrect video link to Arrays and Loops 

- 1-getting-started-lessons/1-intro-to-programming-languages/README.md
- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.es.md
- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.fr.md
- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.gr.md
- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.hi.md
- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.id.md
- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.it.md
- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.ja.md
- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.ko.md
- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.ms.md
- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.nl.md
- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.pt.md
- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.zh-cn.md
- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.zh-tw.md
This time with both commits! (@jlooper)
> Updated web documentation (try 2)

- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.fr.md
Fix a small translation and typo
> Fix typo and small translation

- .gitignore
- 1-getting-started-lessons/2-github-basics/translations/README.fr.md
- 1-getting-started-lessons/translations/README.fr.md
add a french README proposition file for github - basics and add vscode option folder in the gitignore file
> add a french README proposition file for github - basics

- 1-getting-started-lessons/2-github-basics/translations/README.pt.md
- 1-getting-started-lessons/translations/README.pt.md
I have revised and finished translating the Getting started session and got started with JS basics.
> PT translation

- 1-getting-started-lessons/2-github-basics/translations/README.pt.md
- translations/for-teachers.fr.md
update the second image path to display it
> fix image path in pttranslation 1.2

- quiz-app/package-lock.json
- quiz-app/src/App.vue
- quiz-app/src/assets/translations/fr.json
- quiz-app/src/assets/translations/index.js
add the fr option to the select box and add fr.json translation file to the vue quizz app
> propose fr option and translation to the quizz app

- 7-bank-project/solution/translations/README.ko.md
Add translation for `chapter7/solution`. I think this is a missing translation.
> docs: add missing kor translation

- .github/ISSUE_TEMPLATE/translations_checklist.md
there is not a github-basics assignment.md file to translate
> delete github-basics assignment task

- 2-js-basics/3-making-decisions/translations/README.pt.md
- 2-js-basics/3-making-decisions/translations/assignment.pt.md
Hi! 
Translation of : 2-js-basics/3-making-decisions  readme and assigment  to Portuguese
Tks!
#341 - 2-js-basics/3-making-decisio
> Translate js-basics/making decisions Portuguese

- 2-js-basics/1-data-types/translations/README.fr.md
- 2-js-basics/translations/README.fr.md
Hello,
I have started translating the README.md files from section 2 into French. Here are the first two.
Best regards,
Alain.
> Translation of section 2 & 2.1 README.md into French

- 2-js-basics/1-data-types/translations/README.fr.md
> fix small typo

- 2-js-basics/2-functions-methods/translations/assignment.fr.md
> translate 2-2-assignment to french

- 2-js-basics/3-making-decisions/translations/assignment.fr.md
- 2-js-basics/4-arrays-loops/translations/assignment.fr.md
add french translation of assignment.md file in 2-3
> add assignment.fr.md for 2-3 and 2-4

- 3-terrarium/1-intro-to-html/translations/assignment.fr.md
add assignment french translated file for 3-1
> add assignment french translated file for 3-1

- 3-terrarium/2-intro-to-css/translations/assignment.fr.md
add assignment translated file for 3-2
> add assignment translated file for 3-2

- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.pt.md
Hi, guys,
I made an adjustment in the Readme for the Portuguese language translation to help with understanding.
I hope I can help and contribute.
> Correction in translation to pt-br

- 4-typing-game/translations/README.fr.md
- 5-browser-extension/translations/README.fr.md
add assignment.fr.md for 4-typing-game assignment
> [fr] add translation for 4-typing-game assignment, 5-browser-extension base README

- .github/ISSUE_TEMPLATE/translations_checklist.md
Deleting solution base README from 3-terrarium because no translation folder into solution.
> Translation checklist update

- 5-browser-extension/1-about-browsers/translations/assignment.fr.md
> [fr] add 5-1-assignment.fr.md

- 5-browser-extension/start/translations/README.fr.md
suggest translation for 5-start base readme
> [fr] add README.fr.md for 5-start

- 6-space-game/2-drawing-to-canvas/translations/README.zh-tw.md
- 7-bank-project/2-forms/translations/README.zh-tw.md
- 7-bank-project/3-data/translations/README.zh-tw.md
> fix Markdown

- 2-js-basics/4-arrays-loops/translations/README.pt.md
- 2-js-basics/4-arrays-loops/translations/assignment.pt.md
Translated files in array-loops folder
> Translated some files in js-basics to pt

- 5-browser-extension/solution/translation/README.fr.md
translate  5-browser-extension base README / solution base README
> [fr] add README.fr.md for 5-solution

- 6-space-game/translations/README.fr.md
suggest french translation for 6-space-game base README
> [fr] add base README.fr.md for 6-space-game

- 6-space-game/1-introduction/translations/assignment.fr.md
Suggest a french translation for 6-1-assignment.md
> [fr] add 6-1-assignment.fr.md file

- 6-space-game/2-drawing-to-canvas/translations/assignment.fr.md
suggest a translation for 6-2-assignment.md into french
> [fr] add 6-2-assignment.fr.md file

- 7-bank-project/1-template-route/README.md
Bug fix for use of the onLInkClick function in the index.html page by passing in the event object
Reference issue: [Reference issue link](https://github.com/microsoft/Web-Dev-For-Beginners/issues/409)
> Bug fix to pass event object into the onLinkClick

- 6-space-game/3-moving-elements-around/translations/assignment.fr.md
suggest a french translation for 6-3-assignment.md
> [fr] add 6-3-assignment.fr.md file

- 7-bank-project/2-forms/README.md
- 7-bank-project/api/README.md
This PR is meant to address this issue [Issue link](https://github.com/microsoft/Web-Dev-For-Beginners/issues/415)
Better clarification has been provided for the server setups. Thanks
> Clarification on how to setup the Bank server API and the Bank App server for part 2 of the bank app project

- 6-space-game/4-collision-detection/translations/assignment.fr.md
Suggest translation for 6-4-assignment in french
> [fr] add 6-4-assignment.fr.md

- 6-space-game/5-keeping-score/translations/assignment.fr.md
Suggest translation for 6-5-assignment into french
> [fr] add 6-5-assignment.fr.md

- 1-getting-started-lessons/2-github-basics/translations/README.fil.md
Translate the README.md file to Filipino language (_Web-Dev-For-Beginners/1-getting-started-lessons/2-github-basics/translations_)
> Translate README.md to Filipino Language

- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.fil.md
**Add translation to Filipino**
- 1 Getting Started Lessons >1 Intro to Programming Languages > translations | README.fil.md
> Add Translation to Filipino

- 6-space-game/5-keeping-score/translations/README.fr.md
added french readme for Web-Dev-For-Beginners/6-space-game/5-keeping-score/
> added french readme for Web-Dev-For-Beginners/6-space-game/5-keeping-score/

- 3-terrarium/1-intro-to-html/translations/assignment.pt.md
Translation of:  3-terrarium/1-intro-to-html assignment to portuguese.
#341
> Translate terrarium/intro-to-html Portuguese

- 7-bank-project/2-forms/translations/assignment.fr.md
Please find a suggestion of translation for forms assignment (#326)
> Translated Form assignment into French

- 3-terrarium/2-intro-to-css/translations/assignment.pt.md
Translation of: 3-terrarium/2-intro-to-css assignment to portuguese.
#341
> Translate terrarium/intro-to-css Portuguese

- 3-terrarium/3-intro-to-DOM-and-closures/translations/assignment.pt.md
Translation of: 3-terrarium/3-intro-to-DOM-and-closures assignment to portuguese.
#341
> Translate terrarium/intro-to-DOM-and-closures Portuguese

- 3-terrarium/3-intro-to-DOM-and-closures/translations/README.pt.md
Translation of: 3-terrarium/3-intro-to-DOM-and-closures README to portuguese.
#341
> translate intro to DOM and closures README

- 2-js-basics/translations/README.uk.md
Add Ukrainian translation for 2-js-basics/README.md
From issue https://github.com/microsoft/Web-Dev-For-Beginners/issues/489
> Add Ukrainian translation for 2-js-basics/README.md

- 1-getting-started-lessons/translations/README.uk.md
Add Ukrainian translation for 1-getting-started-lessons
From issue https://github.com/microsoft/Web-Dev-For-Beginners/issues/489
> Add translation for 1-getting-started-lessons Ukranian language

- 5-browser-extension/1-about-browsers/translations/README.pt.md
Translation of: 5-browser-extension/about browsers readme to portuguese.
#341
> translate to pt README about browsers

- 7-bank-project/3-data/translations/assignment.fr.md
Translation of 7-bank-project 3-data assignment.md
From issue #326
> French translation for  7-3-assignment

- 5-browser-extension/1-about-browsers/translations/assignment.pt.md
Translation of: 5-browser-extension/about browsers assignment to portuguese.
#341
> translate to pt ASSIGNMENT about browsers

- 3-terrarium/1-intro-to-html/translations/README.fr.md
Fix image and text link, reference fr assignment
> Fix image and text link, reference fr assignment

- README.md
- translations/README.el.md
- translations/README.fil.md
- translations/README.fr.md
- translations/README.pt-BR.md
> Adding pdf working link

- 7-bank-project/2-forms/translations/README.fr.md
Update a image link in 7-2 readme
> Update a image link

- 3-terrarium/2-intro-to-css/translations/README.fr.md
reference the french assignment (assignment.fr.md)
> [fix link] reference the french assignment

- 3-terrarium/3-intro-to-DOM-and-closures/translations/README.fr.md
> Fix image links

- 3-terrarium/2-intro-to-css/translations/README.fr.md
> Fix some image links

- .gitignore
Change "auto generated" to "auto-generated"
> Change "auto generated" to "auto-generated"

- 1-getting-started-lessons/2-github-basics/README.md
Resolved #533 
There was misleading instruction in point 10 and 11. I have resolved it
> Corrected instruction

- 3-terrarium/3-intro-to-DOM-and-closures/translations/README.fr.md
Fix the missing of "du" article in french translation, add precision for closure
> Suggest improved title translation

- 6-space-game/2-drawing-to-canvas/translations/README.fr.md
> fix small typo in french translation

- 6-space-game/5-keeping-score/translations/README.fr.md
> [fr] Fix small typo and image link

- 6-space-game/6-end-condition/translations/README.fr.md
"There are different ways to express and end condition in a game." seems to be better translated by "Il existe différentes manières d'exprimer et de terminer une condition dans un jeu."
> [fr] Review: Suggest more accurate translation

- 7-bank-project/3-data/translations/README.ja.md
> fix a link by deleting space

- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.pt.md
Fix a translation typo in 1-intro-to-programming-languages/translation/README.pt.md
> [pt-BR] Fix a small translation typo

- 4-typing-game/typing-game/README.md
A image link is broken [here](https://microsoft.github.io/Web-Dev-For-Beginners/#/4-typing-game/typing-game/README?id=test-your-application)
> fixed the demo.gif in typing game

- 4-typing-game/translations/READMR.pt-BR.md
Creating a README.md in Brazilian Portuguese in typing-game.
> Add Portuguese Brazilian translation for 4-typing-game

- 1-getting-started-lessons/1-intro-to-programming-languages/README.md
Swapped out some words and rewrote some sentences to increase overall readability without sacrificing the original meaning.
> Improved readability

- 4-typing-game/translations/README.nl.md
I think more Dutch people can read English than Italian, so I think it's better to link to the English lesson.
> Update link to english lesson instead of Italian lesson

- 2-js-basics/3-making-decisions/README.md
- 2-js-basics/4-arrays-loops/README.md
Fixes:
- A broken image link on `2-js-basics/3-making-decisions`
- 2 typos on `2-js-basics/4-arrays-loops`. Loops stop when the condition is NOT met, therefore `false`
> Fix broken image and some typos

- CONTRIBUTING.md
Adding the fact that you should try to specify why you made a certain change when creating a pull request. This change was made at the end of the second paragraph of CONTRIBUTING.md to add this instruction.
> Update CONTRIBUTING.md for PR clarity

- translations/README.fr.md
add Ai link beginners 
Add paragraph for student programme learn and ambassador.
Some link url in a title to delete.
> Correct and modify some links / text

- quiz-app/src/assets/translations/el.json
- quiz-app/src/assets/translations/en.json
- quiz-app/src/assets/translations/es.json
- quiz-app/src/assets/translations/fr.json
- quiz-app/src/assets/translations/hi.json
- quiz-app/src/assets/translations/id.json
- quiz-app/src/assets/translations/it.json
- quiz-app/src/assets/translations/ja.json
- quiz-app/src/assets/translations/ko.json
- quiz-app/src/assets/translations/ms.json
- quiz-app/src/assets/translations/nl.json
- quiz-app/src/assets/translations/ta.json
- quiz-app/src/assets/translations/zh_cn.json
- quiz-app/src/assets/translations/zh_tw.json
Incorrect answer marked as true in first question of prelecture quiz for lesson 3
That answer should not be true unless there exists such a tool (I couldn't find it anywhere)
Edit: incorrect answer also present in other translations
> fix incorrect answer in quiz

- 1-getting-started-lessons/README.md
- 1-getting-started-lessons/translations/README.es.md
- Add `README.es.md` translation for `1-getting-started-lessons`.
- Remove blank lines at the end of the `1-getting-started-lessons\README.md` file.
> Add README translation (ES) for getting-started-lessons

- 5-browser-extension/1-about-browsers/README.md
Fixed a small mistake in the about-browsers chapter.
This PR was created within Hacktoberfest. thank you
> fixed typo in about-browsers chapter

- 1-getting-started-lessons/2-github-basics/translations/README.ko.md
fix a broken link in `1-getting-started-lessons/2-github-basics`
> fix a broken link

- 1-getting-started-lessons/1-intro-to-programming-languages/translations/assignment.pt.md
replacing invalid MDN documentation link with valid link
> HACKTOBERFEST

- 2-js-basics/3-making-decisions/README.md
I changed the comment to explain the working of the loop from past tense to present tense. The condition is true, not was true when it enters the loop and executes the statement.
You can see other comments which are in present tense "// runs if condition is false" but comments in other loops are in past tense "//Condition was true. Code in this block will run.". 
Minor but completes the doc.
> Corrected grammar in explanation

- 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.fr.md
Error of translations in FR and correct sentences for a better FR
> Update and fix Error typos

- 2-js-basics/2-functions-methods/translations/README.es.md
Added some missing Spanish translations for  2-functions-methods
> added spanish translations for 2-functions-methods readme

- 5-browser-extension/start/dist/background.js
- 5-browser-extension/start/src/index.js
The PR un-translates a language confusion caused by a translation to Italian before.
> un-translate code

- index.html
Adding Clarity to capture usage of Docsify GitHub Pages site.
> Add clarity to docsify page

- CONTRIBUTING.md
- README.md
- SECURITY.md
- TRANSLATIONS.md
- for-teachers.md
Corrected some grammatical errors in a few files.
> Corrected some grammatical errors

- 5-browser-extension/3-background-tasks-and-performance/README.md
Corrected grammatically incorrect sentences, punctuations and typos for better readability.
I felt these changes would make this documentation clearer and more understandable than before.
> Corrected grammatically incorrect sentences, punctuations and typos for better readability. (In README.md)

- 2-js-basics/translations/README.hi.md
Added support to right links to remove 404 errors page.
> fixed markdown

- 3-terrarium/translations/README.hi.md
Fixed the redirection of URL for HTML, CSS and Javascript
> Fixed URLs for HTML, CSS, JS

- quiz-app/.eslintrc.js
- quiz-app/babel.config.js
- quiz-app/package-lock.json
- quiz-app/package.json
- quiz-app/src/App.vue
- quiz-app/src/components/Quiz.vue
Updates the dependency and linter settings for the quiz app.
> Update quiz app dependencies

- package-lock.json
- package.json
Updates the package and package-lock files for Docsify site
> Update docsify site

- 6-space-game/translations/README.pt-BR.md
Realized translated the `6-space-game` README to PT-BR (Brazilian Portuguese)
> Added PT-BR Translations for 6-space-game

- CONTRIBUTING.md
This PR adds better grammar to `CONTRIBUTING.md`.
> Update CONTRIBUTING.md with better grammar

- 8-code-editor/1-using-a-code-editor/README.md
Updating `README.md` with better formatting and better grammar.
> Update README.md with better formatting

- 3-terrarium/3-intro-to-DOM-and-closures/README.md
Making the variables in a code block for better formatting.
> Update README.md with code formatting

- translations/for-teachers.es.md
Add translation: for-teachers.es.md
> translation: for-teachers.es.md

- 1-getting-started-lessons/2-github-basics/README.md
> Replaced dead links and modified text accordingly

- 2-js-basics/1-data-types/translations/assignment.az.md
I would also like to do azerbaijani translation.
> add assignment.az.md

- lesson-template/translations/README.fr.md
- lesson-template/translations/assignment.fr.md
Hi microsoft devs :slightly_smiling_face: 
I am creating this Pull Request to help a little with the french translation of this repository, during the Hacktoberfest. 
This Pull Request translates the `README.md` and the `assignment.md` files of the folder `lesson-template` into french..
> Translates the files of the folder lesson-template in french

- 3-terrarium/3-intro-to-DOM-and-closures/translations/README.es.md
- minor proposal on X & Y (paragraph 138)
> Semantic issue (proposal in paragraph 21)

- 1-getting-started-lessons/3-accessibility/translations/README.es.md
- semantic issue (paragraph 26)
- backtick position (paragraph 139)
- typo fixed (paragraph 141)
> Updated URL (line 20)

- 3-terrarium/1-intro-to-html/translations/README.es.md
- 3-terrarium/3-intro-to-DOM-and-closures/translations/README.es.md
- Add omitted section
- Fix images links
- Fix minor translations errors.
> Update spanish translation 3.terrarium

- translations/README.tr.md
This is great tutorial. I translated main README of this curriculum. Thank you!
Btw happy "Hacktoberfest"
> turkish translation of main README.md

- README.md
- translations/README.tr.md
I added help wanted part!
Happy "Hacktoberfest"!
> Add helpwanted part

- 5-browser-extension/solution/src/index.js
Solved the issue #1103 .
Variable 'regionName' not declared, so replaced with 'region' in index.js.
Thank You.
> Variable not declared/ambiguous usage #1103 Solved

- 6-space-game/2-drawing-to-canvas/translations/README.es.md
> Semantic issue (paragraph 09) in Spanish translation

- 2-js-basics/2-functions-methods/translations/README.es.md
- translation issue (paragraph 11)
- semantic issue (paragraph 145)
> Title typo fixed (line 05) in Spanish translation

- 6-space-game/5-keeping-score/translations/README.es.md
- fixed internal URL (paragraph 58)
> Fixed markup formatting (paragraph 30)

- 1-getting-started-lessons/2-github-basics/translations/README.es.md
Updated url of Github Labs
No previous issue related
> Updated url of Labs of Github site (line 324)

- 7-bank-project/4-state-management/translations/README.es.md
* semantic issue (paragraphs 151 & 156)
> Proper translation (paragraph 27 & 214) - Spanish translation

- 7-bank-project/1-template-route/README.md
- 7-bank-project/2-forms/README.md
- 7-bank-project/4-state-management/README.md
- 8-code-editor/1-using-a-code-editor/README.md
> Fix: typos

- 7-bank-project/1-template-route/README.md
Fixes that particular sentence (couldn't find a relevant issue). I was browsing this late at night and got really tripped up by this sentence.
> Added the word "you"

- 7-bank-project/solution/index.html
> Fix 2 issues in bank product.

- 1-getting-started-lessons/1-intro-to-programming-languages/README.md
> Lesson 1 - replacing quiz app with forms quiz

- quiz-app/README.md
Added instructions to run quiz app locally and on Azure
> Added instructions to run quiz app locally and on Azure

- README.md
Included a link to the 'Generative AI with Java' course in the list of related resources in the README.
> Add Generative AI with Java course to README

- 1-getting-started-lessons/3-accessibility/README.md
- Fix mismatched HTML tag: change </span> to </p>
- Ensures accessibility lesson itself has valid HTML markup
- Demonstrates attention to code correctness and web standards
- Single character fix with zero risk to content or functionality
> Fix HTML validation error in accessibility lesson

- 4-typing-game/solution/index.js
> fix: added export default messages in index.js
